### ISSUE TITLE
Database was corrupted, was still in archive mode

### ISSUE THREAD

**Issue by royal85** [xx-labs/xxchain#6]
Nodeid: jIUVIuATWtoge+ssxnHHs4ymTXUPMPi1BoH0DW09g24C

Followed: https://forum.xx.network/t/db-has-been-previously-marked-as-corrupted-attempting-repair/6660

tail -f /opt/xxnetwork/log/chain.log
  30: start_thread
  31: clone

Thread 'tokio-runtime-worker' panicked at 'Critical database error: Custom { kind: Other, error: Error { message: "IO error: No such file or directory: While open a file for random read: /opt/xxnetwork/db/chains/xxnetwork/db/full/61349873.ldb: No such file or directory" } }', /root/.cargo/git/checkouts/substrate-845b7be2a607c074/5d4518f/primitives/database/src/kvdb.rs:29

**Comment by armchairancap** [comment]
Unlikely to be xxChain-only error. Probably the node ran out of RAM and corrupted its filesystem resulting in a loss of files.

Similar problem was [reported for upstream Substrate](https://github.com/paritytech/polkadot-sdk/issues/679#issuecomment-1691882306)
